apiVersion: batch/v1
kind: Job
metadata:
  name: pathnex-batch-job
  namespace: pathnex-app
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: pathnex
                operator: In
                values:
                - batch

      containers:
      - name: batch-container
        image: busybox
        command: ["echo", "Pathnex Batch Job Running"]

      restartPolicy: Never
